#!/bin/bash
#Execution File

if ("$#argv" == "0") then
        set host = "localhost"
        set teamname = "CMUnited"
        set programname  = "orcaclient"
else if ("$#argv" == "1" ) then
        set host = "localhost"
        set teamname = $1
        set programname  = "orcaclient"
else if ("$#argv" == "2" ) then
        set host = $1
        set teamname = $2
        set programname  = "orcaclient"
else if ("$#argv" == "3" ) then
        set host = $2
        set teamname = $3
        set programname  = $1
else
        echo "Usage:  $0 <program-name> <host-name> <team>"
        exit -1
endif

#set simulator_step = 30

echo "Running with the following parameters"
echo "Hostname: " $host
echo "Team: " $teamname
echo "Program: " $programname
#echo "Sim_step: " $simulator_step

$programname -file client.conf -file server.conf -host $host -team_name $teamname -goalie &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep
$programname -file client.conf -file server.conf -host $host -team_name $teamname &
quicksleep

#waitforq
#if ( -e /usr/ucb/ps ) then 
#  kill `/usr/ucb/ps ax | grep $programname | grep -v grep | awk '{print $1}'`
#else
#kill -9 `ps ax | grep $programname | grep -v grep | awk '{print $1}'`
#endif
